### ISSUE TITLE
Too large specular

### ISSUE THREAD

**Issue by AlexandreLamure** [Pleuvens/RayTracer#1]
https://github.com/Pleuvens/RayTracer/blob/837b9a9960effc6f45f19917822e5163c25afd79/src/scene.cc#L61

This could be the reason of the bad specular.
Instead of a ` Vec3f::sum(reflect, dir)`, you should try `dotProduct(reflect, -dir)`.

Take a look at this for reference:
https://www.scratchapixel.com/lessons/3d-basic-rendering/phong-shader-BRDF

**Comment by Pleuvens** [comment]
Yeah it seems to be one of the issues but I think there are some more issues. I think I need to rework it from the implementation of the specular where the first issue seems to originate
